name: Renovate Bot
on:
  schedule:
  - cron: '0 3 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.0.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
